"""add_explicacao_xai_to_noticiacache

Revision ID: 1a7f376d5268
Revises: 75eb7f754be1
Create Date: 2026-10-08 08:41:05.737620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7f376d5268'
down_revision: Union[str, Sequence[str], None] = '75eb7f754be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias_cache', sa.Column('explicacao_xai', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noticias_cache', 'explicacao_xai')
    # ### end Alembic commands ###
