"""Cria_tabelas_de_cache_e_votos

Revision ID: 266b071befdc
Revises: 
Create Date: 2026-10-06 14:31:04.097126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266b071befdc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticias_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('score_ml', sa.Float(), nullable=True),
    sa.Column('data_processamento', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_noticias_cache_id'), 'noticias_cache', ['id'], unique=False)
    op.create_index(op.f('ix_noticias_cache_url'), 'noticias_cache', ['url'], unique=True)
    op.create_table('votos_comunidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_noticia', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.String(), nullable=False),
    sa.Column('voto', sa.Integer(), nullable=False),
    sa.Column('peso_voto', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_noticia'], ['noticias_cache.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votos_comunidade_id'), 'votos_comunidade', ['id'], unique=False)
    op.create_index(op.f('ix_votos_comunidade_id_usuario'), 'votos_comunidade', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votos_comunidade_id_usuario'), table_name='votos_comunidade')
    op.drop_index(op.f('ix_votos_comunidade_id'), table_name='votos_comunidade')
    op.drop_table('votos_comunidade')
    op.drop_index(op.f('ix_noticias_cache_url'), table_name='noticias_cache')
    op.drop_index(op.f('ix_noticias_cache_id'), table_name='noticias_cache')
    op.drop_table('noticias_cache')
    # ### end Alembic commands ###
