"""Add bias_label and bias_score to NoticiaCache

Revision ID: 75eb7f754be1
Revises: 266b071befdc
Create Date: 2026-10-06 15:16:25.204326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75eb7f754be1'
down_revision: Union[str, Sequence[str], None] = '266b071befdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias_cache', sa.Column('bias_label', sa.String(), nullable=True))
    op.add_column('noticias_cache', sa.Column('bias_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noticias_cache', 'bias_score')
    op.drop_column('noticias_cache', 'bias_label')
    # ### end Alembic commands ###
